os: 
  - osx

language: python
python:
  - "2.7"

before_install:
  - which python

install:
  - brew install wget
  - wget https://www.python.org/ftp/python/2.7.9/python-2.7.9-macosx10.6.pkg
  - sudo installer -pkg python-2.7.9-macosx10.6.pkg -target /

script:
  - which python
